### ISSUE TITLE
Cannot reconnect after server crash or shutdown

### ISSUE THREAD

**Issue by ittech25** [1998dell/Python-Reverse-Shell-2020#1]
Cannot reconnect after server crash or shutdown
Loop 
![image](https://user-images.githubusercontent.com/63135414/83963642-cc73e500-a8d1-11ea-9c83-da48dc54f331.png)

**Comment by 1998dell** [comment]
just try to close the attacker and restart again.. or add task scheduler in victim side

**Comment by ittech25** [comment]
Ok, Thanks
